---
- name: Verify
  hosts: all

  tasks:
    - name: Collect package facts.
      package_facts:
        manager: "auto"

    - name: Verify zathura is installed.
      assert:
        that:
          - "'zathura' in ansible_facts.packages"
        success_msg: "Zathura is installed."
        fail_msg: "Zathura is not installed."

    - name: Verify zathura-pdf-poppler is installed.
      assert:
        that:
          - "'zathura-pdf-poppler' in ansible_facts.packages"
        success_msg: "'zathura-pdf-poppler' is installed."
        fail_msg: "zathura-pdf-poppler is not installed."
